import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790293900000 implements MigrationInterface {
    name = 'InitialSchema1790293900000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."referrals_status_enum" AS ENUM('pending', 'completed', 'expired')`);
        await queryRunner.query(`CREATE TABLE "referrals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referralCode" character varying NOT NULL, "referrerId" uuid NOT NULL, "refereeId" uuid, "status" "public"."referrals_status_enum" NOT NULL DEFAULT 'pending', "completedAt" TIMESTAMP, "rewardDetails" jsonb, "isRewardDistributed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, CONSTRAINT "UQ_13a1bad9eef9e5cfa4b61765261" UNIQUE ("referralCode"), CONSTRAINT "PK_ea9980e34f738b6252817326c08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'player', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying, "password" character varying, "avatar" character varying, "tokens" integer NOT NULL DEFAULT '0', "firstname" character varying, "lastname" character varying, "totalScore" integer NOT NULL DEFAULT '0', "gamesPlayed" integer NOT NULL DEFAULT '0', "gamesWon" integer NOT NULL DEFAULT '0', "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "points" integer NOT NULL DEFAULT '0', "stellarAddress" character varying(56), "referralCode" character varying, "referralStats" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_6ca644d6db1d091834d0d181c2f" UNIQUE ("stellarAddress"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tournament" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "rules" json, CONSTRAINT "PK_449f912ba2b62be003f0c22e767" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."game_sessions_status_enum" AS ENUM('waiting', 'in_progress', 'completed', 'cancelled', 'expired', 'abandoned', 'paused')`);
        await queryRunner.query(`CREATE TABLE "game_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gameMode" character varying, "startTime" TIMESTAMP NOT NULL DEFAULT now(), "endTime" TIMESTAMP, "status" "public"."game_sessions_status_enum" NOT NULL DEFAULT 'in_progress', "maxPlayers" integer NOT NULL DEFAULT '4', "score" numeric, "location" character varying, "metadata" json, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tournamentId" uuid, CONSTRAINT "PK_e25fa82d55744e55000c3288fdc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "code" character varying NOT NULL, "capacity" integer NOT NULL DEFAULT '10', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_368d83b661b9670e7be1bbb9cdd" UNIQUE ("code"), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "playerId" uuid NOT NULL, "roomId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "leftAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9a7dfb75f51c75ce1aff8b4f854" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."players_status_enum" AS ENUM('online', 'away', 'busy', 'offline')`);
        await queryRunner.query(`CREATE TABLE "players" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying, "firstname" character varying, "lastname" character varying, "email" character varying, "status" "public"."players_status_enum" NOT NULL DEFAULT 'offline', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "chatRoomId" uuid, CONSTRAINT "UQ_0ba988c87a279b5067d273c5924" UNIQUE ("username"), CONSTRAINT "UQ_3abeb86b19703d782f0beff84c0" UNIQUE ("email"), CONSTRAINT "PK_de22b8fdeee0c33ab55ae71da3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c69082bd83bffeb71b0f455bd59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leaderboards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rank" integer NOT NULL DEFAULT '0', "score" numeric NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_190f95e31621935228328d6c20a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstActiveAt" TIMESTAMP NOT NULL DEFAULT now(), "lastActiveAt" TIMESTAMP NOT NULL DEFAULT now(), "totalSessions" integer NOT NULL DEFAULT '0', "totalSessionDuration" integer NOT NULL DEFAULT '0', "activeToday" boolean NOT NULL DEFAULT false, "activeThisWeek" boolean NOT NULL DEFAULT false, "activeThisMonth" boolean NOT NULL DEFAULT false, "retentionDays" text, "userId" uuid, CONSTRAINT "PK_daec6d19443689bda7d7785dff5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."achievement_category_enum" AS ENUM('STREAK', 'SCORE', 'GENRE', 'SOCIAL', 'MISC')`);
        await queryRunner.query(`CREATE TABLE "achievement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "icon" character varying NOT NULL, "category" "public"."achievement_category_enum" NOT NULL, "pointsValue" integer NOT NULL, "criteria" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_441339f40e8ce717525a381671e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_achievement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "progress" double precision NOT NULL, "isCompleted" boolean NOT NULL DEFAULT false, "unlockedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "achievementId" uuid, CONSTRAINT "PK_99df4f0afe2d706c05004854aa5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_engagement_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "sessionCount" integer NOT NULL, "sessionDuration" double precision NOT NULL, "activityData" json NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_67fae3be20d12d739e27d97b81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3553b0aad43bdfe497dcd7cc86" ON "player_engagement_metrics" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb2ca8964c8aa32e3cc43a9dee" ON "player_engagement_metrics" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "user_progression_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "level" integer NOT NULL, "experience" double precision NOT NULL, "achievements" text NOT NULL, "progressionData" json NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_c81c3b38153112088120b3c6ae4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77d0085801058cf4f3280aa456" ON "user_progression_metrics" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0c4f43fe640b3a7e1e070833a" ON "user_progression_metrics" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "song_category_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "categoryId" character varying NOT NULL, "categoryName" character varying NOT NULL, "playCount" integer NOT NULL, "uniqueUsers" integer NOT NULL, "averagePlayTime" double precision NOT NULL, "popularityTrend" json NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_269d5cac7152caf3f0d8ff630d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a7ed52c492d5bcd9ac6a1bece" ON "song_category_metrics" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ba6fa4785e1ad503bd8fedf79" ON "song_category_metrics" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "tokenHash" character varying(64) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "usedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6a19d4b4f6c62dcd29daa497e" ON "password_reset_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1143abb8c3fad8b06dd857a8c9" ON "password_reset_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE TABLE "config_entry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" json NOT NULL, "version" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "validationRules" json, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b73012ebb09a6bef3bd87f6398d" UNIQUE ("key"), CONSTRAINT "PK_9f3af1247edda0552a173ca2ac8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "config_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "oldValue" json NOT NULL, "newValue" json NOT NULL, "changedBy" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "configId" uuid, CONSTRAINT "PK_f7b9ead6fa76fec4391d14e6339" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "structure" json NOT NULL, "type" character varying NOT NULL, "rules" json NOT NULL, "difficultyRange" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fbae2ac36bd9b5e1e793b957b7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "generated_content" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" json NOT NULL, "difficulty" integer NOT NULL, "status" character varying NOT NULL, "usageCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "templateId" uuid, CONSTRAINT "PK_175d96212ff70c5ea9112a30928" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "price" integer NOT NULL, "type" character varying NOT NULL, "image" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8d520cf8af78e9dd5bc47943c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."coupon_discounttype_enum" AS ENUM('percentage', 'fixed_amount', 'buy_x_get_y', 'free_shipping')`);
        await queryRunner.query(`CREATE TYPE "public"."coupon_status_enum" AS ENUM('active', 'inactive', 'expired', 'depleted')`);
        await queryRunner.query(`CREATE TABLE "coupon" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "description" character varying NOT NULL, "discountType" "public"."coupon_discounttype_enum" NOT NULL DEFAULT 'percentage', "discountValue" numeric(10,2) NOT NULL DEFAULT '0', "minimumPurchaseAmount" integer, "maximumDiscountAmount" integer, "status" "public"."coupon_status_enum" NOT NULL DEFAULT 'active', "startDate" TIMESTAMP, "endDate" TIMESTAMP, "maxUsesPerUser" integer NOT NULL DEFAULT '1', "isFirstTimeOnly" boolean NOT NULL DEFAULT false, "maxTotalUses" integer, "currentUses" integer NOT NULL DEFAULT '0', "buyQuantity" integer, "getQuantity" integer, "isGlobal" boolean NOT NULL DEFAULT false, "metadata" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, CONSTRAINT "UQ_62d3c5b0ce63a82c48e86d904bc" UNIQUE ("code"), CONSTRAINT "PK_fcbe9d72b60eed35f46dc35a682" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupon_usage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "discountAmount" numeric(10,2) NOT NULL, "orderTotal" numeric(10,2) NOT NULL, "usedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" text, "couponId" uuid, "userId" uuid, CONSTRAINT "PK_5727b2e426ee3e63c3f5e200e61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "backup_metadata" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "backupId" character varying NOT NULL, "filename" character varying NOT NULL, "location" character varying NOT NULL, "size" bigint NOT NULL, "migrationId" character varying, "available" boolean NOT NULL DEFAULT true, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0028cf7ad7ae3633311c7d00a21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5985996616f6f9f41503cb82d" ON "backup_metadata" ("backupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_887cd1659f8b661e1ea7c9804f" ON "backup_metadata" ("migrationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_89fa5b280771988b72142ffc91" ON "backup_metadata" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "migration_lock" ("id" character varying NOT NULL, "lockedBy" character varying NOT NULL, "lockedAt" TIMESTAMP NOT NULL, "expiresAt" TIMESTAMP, "isExecuting" boolean NOT NULL DEFAULT false, "currentMigrationId" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bfd4d7f3de4a0da2f1c84697ce6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "custom_game_modes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "rules" json NOT NULL, "isPublic" boolean NOT NULL, "votes" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "creatorId" uuid, CONSTRAINT "PK_9f3216b2fc0c97ec1828d46d391" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "migration_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "migrationId" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "dependencies" json, "appliedAt" TIMESTAMP NOT NULL, "success" boolean NOT NULL DEFAULT true, "error" character varying, "rolledBack" boolean NOT NULL DEFAULT false, "rolledBackAt" TIMESTAMP, "backupId" character varying, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_63ad381728693434caed4dd922e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb82c5bb484e891ad7c43c9cb0" ON "migration_history" ("migrationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_783c305cc0c33e930cbbe749ef" ON "migration_history" ("appliedAt") `);
        await queryRunner.query(`CREATE TABLE "difficulties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_192135d73f3f3320bd4fb970a07" UNIQUE ("value"), CONSTRAINT "PK_4c3dd46c9ed9b426d0307e45b3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ip" character varying NOT NULL, "city" character varying, "region" character varying, "country" character varying, "countryCode" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "timezone" character varying, "isp" character varying, "asn" character varying, "additionalData" json, "isRestricted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5de21ea3c57035888d98d5bc4c" ON "locations" ("ip") `);
        await queryRunner.query(`CREATE TABLE "location_access" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying, "ipAddress" character varying NOT NULL, "endpoint" character varying NOT NULL, "userAgent" character varying, "isBlocked" boolean NOT NULL DEFAULT false, "blockReason" character varying, "accessTime" TIMESTAMP NOT NULL DEFAULT now(), "locationId" uuid, CONSTRAINT "PK_d267b7cd47696cb308985fc4096" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66d338c28e4f3fbd870043b9bf" ON "location_access" ("ipAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc34d4f79551898149eadc54b5" ON "location_access" ("accessTime") `);
        await queryRunner.query(`CREATE TABLE "token_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "totalSupply" double precision NOT NULL, "circulation" double precision NOT NULL, "transactions" integer NOT NULL, "averageHolding" double precision NOT NULL, "distributionData" json NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_778f18ec4353bd9f29ed5cbfb5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_301ed31d932bcfdd22ed87ed59" ON "token_metrics" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "leaderboard_round_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roundId" character varying NOT NULL, "playerId" character varying NOT NULL, "address" character varying, "username" character varying NOT NULL, "genre" character varying NOT NULL, "won" boolean NOT NULL, "streakAfter" integer NOT NULL DEFAULT '0', "playedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_77466de886694eb20939652cf6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cda49a36795f20bc974f9d1a15" ON "leaderboard_round_results" ("roundId") `);
        await queryRunner.query(`CREATE INDEX "IDX_94015b1d60e640eb05a1a7944b" ON "leaderboard_round_results" ("playerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4af4449083c75c65d82351d150" ON "leaderboard_round_results" ("genre", "playedAt") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "type" character varying NOT NULL, "message" text NOT NULL, "metadata" json, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE TABLE "game_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "gameId" character varying NOT NULL, "gameData" json NOT NULL, "score" integer NOT NULL, "timeSpent" integer NOT NULL, "achievements" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d45049161e874555e7cfe325afe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d7c521e6b5e4ed12810185797" ON "game_results" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e63bfae8ba1bbd2614be36731a" ON "game_results" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "power_up" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "duration" integer NOT NULL, "price" integer NOT NULL, CONSTRAINT "PK_5056ddc7209130fecd3b1b16b2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "power_up_purchase" ("id" SERIAL NOT NULL, "purchaseDate" TIMESTAMP NOT NULL, "expirationDate" TIMESTAMP NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "powerUpId" integer, "userId" uuid, CONSTRAINT "PK_985566add89731b27913bcc3622" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_skill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "level" integer NOT NULL DEFAULT '0', "experience" integer NOT NULL DEFAULT '0', "playerStatsId" uuid, CONSTRAINT "PK_3ec1b254412eccdbab22544ef21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_stats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "totalXp" integer NOT NULL DEFAULT '0', "level" integer NOT NULL DEFAULT '1', "skillRating" integer NOT NULL DEFAULT '0', "rank" character varying NOT NULL, "achievements" json NOT NULL, "milestones" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_22e2d8ec820a98efbfdbf84d925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_level" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "xpGained" integer NOT NULL, "totalXp" integer NOT NULL, "achievedAt" TIMESTAMP NOT NULL DEFAULT now(), "playerStatsId" uuid, CONSTRAINT "PK_ddf5f947197b75e19ac2a3b327e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."practice_progress_genre_enum" AS ENUM('HipHop', 'Pop', 'Rock', 'RnB', 'Electronic', 'Classical', 'Jazz', 'Country', 'Blues', 'Reggae', 'Afrobeat', 'Gospel', 'Folk')`);
        await queryRunner.query(`CREATE TABLE "practice_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "genre" "public"."practice_progress_genre_enum" NOT NULL, "totalSessions" integer NOT NULL DEFAULT '0', "totalItems" integer NOT NULL DEFAULT '0', "correctAnswers" integer NOT NULL DEFAULT '0', "averageScore" numeric(5,2) NOT NULL DEFAULT '0', "averageTimePerItem" numeric(5,2) NOT NULL DEFAULT '0', "masteredItems" integer NOT NULL DEFAULT '0', "strengthsBySubcategory" text NOT NULL DEFAULT '{}', "weaknessesBySubcategory" text NOT NULL DEFAULT '{}', "learningPath" text NOT NULL DEFAULT '[]', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_5bf68852dcc968d63c7bb92a62a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "category" character varying, CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."songs_status_enum" AS ENUM('draft', 'approved', 'on_chain')`);
        await queryRunner.query(`CREATE TYPE "public"."songs_genre_enum" AS ENUM('HipHop', 'Pop', 'Rock', 'RnB', 'Electronic', 'Classical', 'Jazz', 'Country', 'Blues', 'Reggae', 'Afrobeat', 'Gospel', 'Folk')`);
        await queryRunner.query(`CREATE TYPE "public"."songs_difficulty_enum" AS ENUM('easy', 'medium', 'hard')`);
        await queryRunner.query(`CREATE TABLE "songs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "onChainCardId" bigint, "status" "public"."songs_status_enum" NOT NULL DEFAULT 'draft', "genre" "public"."songs_genre_enum" NOT NULL, "artist" character varying NOT NULL, "title" character varying NOT NULL, "year" integer NOT NULL, "lyrics" text NOT NULL, "difficulty" "public"."songs_difficulty_enum" NOT NULL DEFAULT 'medium', "source" text NOT NULL, "license" character varying NOT NULL, "playCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f4eeba1354149cfe5f0907d1d88" UNIQUE ("onChainCardId"), CONSTRAINT "PK_e504ce8ad2e291d3a1d8f1ea2f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2e69e62f014eed5c621710bdd0" ON "songs" ("artist", "title") `);
        await queryRunner.query(`CREATE TABLE "questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lyricSnippet" text NOT NULL, "options" text NOT NULL, "correctAnswer" integer NOT NULL, "difficulty" integer NOT NULL, "points" integer NOT NULL, "timeLimit" integer NOT NULL, "timesUsed" integer NOT NULL DEFAULT '0', "correctAnswers" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "songId" uuid, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "patterns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "replayId" uuid NOT NULL, "playerId" character varying NOT NULL, "type" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "confidence" character varying NOT NULL, "data" jsonb NOT NULL, "frequency" double precision, "isCommon" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afb8e3087247ebfc0f30a682a9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "replayId" uuid NOT NULL, "playerId" character varying NOT NULL, "title" character varying NOT NULL, "description" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "assignedTo" character varying, "actionTaken" character varying NOT NULL DEFAULT 'none', "actionNotes" character varying, "isAutoGenerated" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "resolvedAt" TIMESTAMP, CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "replays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gameId" character varying NOT NULL, "matchId" character varying NOT NULL, "playerIds" text NOT NULL, "gameVersion" character varying NOT NULL, "mapId" character varying, "gameMode" character varying, "durationSeconds" integer NOT NULL, "storageUrl" character varying NOT NULL, "hasBeenAnalyzed" boolean NOT NULL DEFAULT false, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "analyzedAt" TIMESTAMP, CONSTRAINT "PK_25cfbee6682178c5c90149cbb3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "anomalies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "replayId" uuid NOT NULL, "playerId" character varying NOT NULL, "type" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "severity" character varying NOT NULL, "data" jsonb NOT NULL, "confidenceScore" double precision NOT NULL, "timeIndexInReplay" integer, "isVerified" boolean NOT NULL DEFAULT false, "detectedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_85dc6428a06c59628d40b1c5f8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scoring" ("id" SERIAL NOT NULL, "userId" character varying NOT NULL, "score" integer NOT NULL DEFAULT '0', "ranking" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76879d276229eb941c4f256d9e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "game_state" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gameId" character varying NOT NULL, "playerId" character varying NOT NULL, "state" json NOT NULL, "version" integer NOT NULL, "checksum" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isValid" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_e7b8f9fb87d56841a7aaa284f52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_genre_preferences_genre_enum" AS ENUM('HipHop', 'Pop', 'Rock', 'RnB', 'Electronic', 'Classical', 'Jazz', 'Country', 'Blues', 'Reggae', 'Afrobeat', 'Gospel', 'Folk')`);
        await queryRunner.query(`CREATE TABLE "user_genre_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "genre" "public"."user_genre_preferences_genre_enum" NOT NULL, "preferenceScore" double precision NOT NULL DEFAULT '0', "playCount" integer NOT NULL DEFAULT '0', "averagePerformance" double precision NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c473a15a8f4ed6b6482fadd3f2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9655d1d49ca2af5f7a350cfa1c" ON "user_genre_preferences" ("userId", "genre") `);
        await queryRunner.query(`CREATE TABLE "state_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "previousState" json NOT NULL, "newState" json NOT NULL, "triggeredBy" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "gameStateId" uuid, CONSTRAINT "PK_18a92433314942cdfc9be280f93" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL DEFAULT '1', "acquiredAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "itemId" uuid, CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" integer NOT NULL, "currency" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying NOT NULL DEFAULT 'COMPLETED', "userId" uuid, "itemId" uuid, CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sync_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "syncRecordId" uuid NOT NULL, "version" integer NOT NULL, "data" jsonb NOT NULL, "deviceId" character varying, "strategyUsed" character varying, "delta" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e929aeba0c2244394dab3a7514c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41c20ca17ff2890de04f660ef7" ON "sync_history" ("syncRecordId") `);
        await queryRunner.query(`CREATE TABLE "sync_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "dataType" character varying NOT NULL, "version" integer NOT NULL, "data" jsonb NOT NULL, "lastSyncedAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57204e18793ddafb1a18a4915fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbce738cd9b37246a250603447" ON "sync_records" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_14b0fcce98762aa70bb9cfd577" ON "sync_records" ("dataType") `);
        await queryRunner.query(`CREATE TYPE "public"."wagers_status_enum" AS ENUM('escrowed', 'won', 'lost', 'refunded', 'claimed')`);
        await queryRunner.query(`CREATE TABLE "wagers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roundId" character varying NOT NULL, "player" character varying NOT NULL, "amount" numeric(39,0) NOT NULL, "asset" character varying NOT NULL DEFAULT 'native', "txHash" character varying, "status" "public"."wagers_status_enum" NOT NULL DEFAULT 'escrowed', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2a22416f9356af58909ae940bb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2c9659e7f5ea5b2994fbe81e1" ON "wagers" ("roundId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dadc1a0a962be5e8d09b33c4e6" ON "wagers" ("player") `);
        await queryRunner.query(`CREATE TABLE "share_analytics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shareId" character varying NOT NULL, "views" integer NOT NULL DEFAULT '0', "clicks" integer NOT NULL DEFAULT '0', "reshares" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3fdb2009343efd8d36c87d260ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "type" character varying NOT NULL, "metadata" json, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba42b1223c698e594af188983f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shares_type_enum" AS ENUM('lyric_card', 'game_result', 'achievement', 'playlist')`);
        await queryRunner.query(`CREATE TYPE "public"."shares_platform_enum" AS ENUM('twitter', 'facebook', 'discord', 'internal')`);
        await queryRunner.query(`CREATE TABLE "shares" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "type" "public"."shares_type_enum" NOT NULL, "contentId" character varying NOT NULL, "contentType" character varying NOT NULL, "title" character varying, "description" character varying, "thumbnailUrl" character varying, "shareLink" character varying NOT NULL, "previewData" json, "platform" "public"."shares_platform_enum" NOT NULL DEFAULT 'internal', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b88473409066c43c2ccb1894a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "artist" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "biography" text NOT NULL, "genre" character varying NOT NULL, "birthYear" integer NOT NULL, CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genre_history" ("id" SERIAL NOT NULL, "genre" character varying NOT NULL, "history" text NOT NULL, CONSTRAINT "PK_ff6ea3227bbcac3165c0483a78c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quiz" ("id" SERIAL NOT NULL, "question" character varying NOT NULL, "options" text array NOT NULL, "correctAnswer" character varying NOT NULL, CONSTRAINT "PK_422d974e7217414e029b3e641d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "music_lesson" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "genre" character varying NOT NULL, "difficulty" character varying NOT NULL, CONSTRAINT "PK_240b739611373e75c4e9c292880" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_progress" ("id" SERIAL NOT NULL, "completed" boolean NOT NULL DEFAULT false, "userId" uuid, "lessonId" integer, CONSTRAINT "PK_e6223ebbc5f8f5fce40e0193de1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tournament_participants_users" ("tournamentId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_6eb231f50bb8e14835eeb76cf8f" PRIMARY KEY ("tournamentId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4e830a879d5346795b76e1047" ON "tournament_participants_users" ("tournamentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_763cd9da7c8b086ab1a0f75331" ON "tournament_participants_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "players_game_sessions_game_sessions" ("playersId" uuid NOT NULL, "gameSessionsId" uuid NOT NULL, CONSTRAINT "PK_db0fcc64007113305ed5ebc65ef" PRIMARY KEY ("playersId", "gameSessionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4cd87de62a2c41e479f0e9e3e7" ON "players_game_sessions_game_sessions" ("playersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fec553a0f27c6f5da0a56d2b98" ON "players_game_sessions_game_sessions" ("gameSessionsId") `);
        await queryRunner.query(`CREATE TABLE "coupon_applicable_items_store_item" ("couponId" uuid NOT NULL, "storeItemId" uuid NOT NULL, CONSTRAINT "PK_9b25bd36765750fac18e6f09531" PRIMARY KEY ("couponId", "storeItemId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c2e96f0074f11d1a9917dd4f4" ON "coupon_applicable_items_store_item" ("couponId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9c3f442fe422fb48f6b6ae933" ON "coupon_applicable_items_store_item" ("storeItemId") `);
        await queryRunner.query(`CREATE TABLE "song_tags" ("songsId" uuid NOT NULL, "tagsId" uuid NOT NULL, CONSTRAINT "PK_9b2ca5f9fab31765d6793e7b310" PRIMARY KEY ("songsId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ce5ba390f8fc32878ee8a0cd6" ON "song_tags" ("songsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_669266aed514df75c08a134bce" ON "song_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "reports_anomalies_anomalies" ("reportsId" uuid NOT NULL, "anomaliesId" uuid NOT NULL, CONSTRAINT "PK_b2bd9991e625202bb64a7c4b346" PRIMARY KEY ("reportsId", "anomaliesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bff99233fe88934d1d9ec5c50b" ON "reports_anomalies_anomalies" ("reportsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_00d4d9d863ebe837fc0bb9bbda" ON "reports_anomalies_anomalies" ("anomaliesId") `);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_59de462f9ce130da142e3b5a9f4" FOREIGN KEY ("referrerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_70ff19adfe86eac7f48e1524973" FOREIGN KEY ("refereeId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_sessions" ADD CONSTRAINT "FK_4fa37b6649feb118785237853e5" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_rooms" ADD CONSTRAINT "FK_85404222998d4d527b2144180f0" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_rooms" ADD CONSTRAINT "FK_baf7e3898baabc477aa4d8058a6" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_3c658637d779605a5f17a018c81" FOREIGN KEY ("chatRoomId") REFERENCES "chat_rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_activity" ADD CONSTRAINT "FK_c8d8d7cfc6e3433e725339c952b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievement" ADD CONSTRAINT "FK_2a418515c335cab7c5ba70c28b3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievement" ADD CONSTRAINT "FK_843ecd1965f1aac694875674a18" FOREIGN KEY ("achievementId") REFERENCES "achievement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "config_audit" ADD CONSTRAINT "FK_ff0bc659e4f0abbecd84b3c8006" FOREIGN KEY ("configId") REFERENCES "config_entry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "generated_content" ADD CONSTRAINT "FK_458f45d0fa6ef378f16113f3680" FOREIGN KEY ("templateId") REFERENCES "template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_18b10b5df91ce11abe764e6edda" FOREIGN KEY ("couponId") REFERENCES "coupon"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_302670923e49b67d7f4e9772f64" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_game_modes" ADD CONSTRAINT "FK_c9488b539ed99f0866be8c7c84d" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_access" ADD CONSTRAINT "FK_70c1b3a369f14032a95d797a975" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "power_up_purchase" ADD CONSTRAINT "FK_544e9b97de456bac13b06bf2d74" FOREIGN KEY ("powerUpId") REFERENCES "power_up"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "power_up_purchase" ADD CONSTRAINT "FK_473ea9d9368c7468ff97803b245" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_skill" ADD CONSTRAINT "FK_3368acdf2e65b24118fbbee2947" FOREIGN KEY ("playerStatsId") REFERENCES "player_stats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_level" ADD CONSTRAINT "FK_7d1fb4880813f3331b0bbd50004" FOREIGN KEY ("playerStatsId") REFERENCES "player_stats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_progress" ADD CONSTRAINT "FK_fed92359515dfd602a1d8e04829" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_8f08ff70d9c14259219201ad445" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patterns" ADD CONSTRAINT "FK_e5c12879ffcd0cbbac1dfca738c" FOREIGN KEY ("replayId") REFERENCES "replays"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_4fe5cb57be94f7163c71ab3807c" FOREIGN KEY ("replayId") REFERENCES "replays"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anomalies" ADD CONSTRAINT "FK_e6a5e625a5305387f8565e3869f" FOREIGN KEY ("replayId") REFERENCES "replays"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "state_audit" ADD CONSTRAINT "FK_a865049511f1e068f85cc5cacec" FOREIGN KEY ("gameStateId") REFERENCES "game_state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_fe4917e809e078929fe517ab762" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_6227c61eff466680f9bb9933305" FOREIGN KEY ("itemId") REFERENCES "store_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_605baeb040ff0fae995404cea37" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_fae09ef9b1765a71a91475f8ba7" FOREIGN KEY ("itemId") REFERENCES "store_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_history" ADD CONSTRAINT "FK_41c20ca17ff2890de04f660ef76" FOREIGN KEY ("syncRecordId") REFERENCES "sync_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_progress" ADD CONSTRAINT "FK_eb4349e70765bb218bb4f833f68" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_progress" ADD CONSTRAINT "FK_df13299d2740b302dd44a368df9" FOREIGN KEY ("lessonId") REFERENCES "music_lesson"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_participants_users" ADD CONSTRAINT "FK_c4e830a879d5346795b76e1047f" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tournament_participants_users" ADD CONSTRAINT "FK_763cd9da7c8b086ab1a0f75331f" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "players_game_sessions_game_sessions" ADD CONSTRAINT "FK_4cd87de62a2c41e479f0e9e3e71" FOREIGN KEY ("playersId") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "players_game_sessions_game_sessions" ADD CONSTRAINT "FK_fec553a0f27c6f5da0a56d2b988" FOREIGN KEY ("gameSessionsId") REFERENCES "game_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_applicable_items_store_item" ADD CONSTRAINT "FK_4c2e96f0074f11d1a9917dd4f4a" FOREIGN KEY ("couponId") REFERENCES "coupon"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "coupon_applicable_items_store_item" ADD CONSTRAINT "FK_e9c3f442fe422fb48f6b6ae9330" FOREIGN KEY ("storeItemId") REFERENCES "store_item"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_tags" ADD CONSTRAINT "FK_9ce5ba390f8fc32878ee8a0cd6b" FOREIGN KEY ("songsId") REFERENCES "songs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_tags" ADD CONSTRAINT "FK_669266aed514df75c08a134bce9" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports_anomalies_anomalies" ADD CONSTRAINT "FK_bff99233fe88934d1d9ec5c50b9" FOREIGN KEY ("reportsId") REFERENCES "reports"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reports_anomalies_anomalies" ADD CONSTRAINT "FK_00d4d9d863ebe837fc0bb9bbda2" FOREIGN KEY ("anomaliesId") REFERENCES "anomalies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reports_anomalies_anomalies" DROP CONSTRAINT "FK_00d4d9d863ebe837fc0bb9bbda2"`);
        await queryRunner.query(`ALTER TABLE "reports_anomalies_anomalies" DROP CONSTRAINT "FK_bff99233fe88934d1d9ec5c50b9"`);
        await queryRunner.query(`ALTER TABLE "song_tags" DROP CONSTRAINT "FK_669266aed514df75c08a134bce9"`);
        await queryRunner.query(`ALTER TABLE "song_tags" DROP CONSTRAINT "FK_9ce5ba390f8fc32878ee8a0cd6b"`);
        await queryRunner.query(`ALTER TABLE "coupon_applicable_items_store_item" DROP CONSTRAINT "FK_e9c3f442fe422fb48f6b6ae9330"`);
        await queryRunner.query(`ALTER TABLE "coupon_applicable_items_store_item" DROP CONSTRAINT "FK_4c2e96f0074f11d1a9917dd4f4a"`);
        await queryRunner.query(`ALTER TABLE "players_game_sessions_game_sessions" DROP CONSTRAINT "FK_fec553a0f27c6f5da0a56d2b988"`);
        await queryRunner.query(`ALTER TABLE "players_game_sessions_game_sessions" DROP CONSTRAINT "FK_4cd87de62a2c41e479f0e9e3e71"`);
        await queryRunner.query(`ALTER TABLE "tournament_participants_users" DROP CONSTRAINT "FK_763cd9da7c8b086ab1a0f75331f"`);
        await queryRunner.query(`ALTER TABLE "tournament_participants_users" DROP CONSTRAINT "FK_c4e830a879d5346795b76e1047f"`);
        await queryRunner.query(`ALTER TABLE "lesson_progress" DROP CONSTRAINT "FK_df13299d2740b302dd44a368df9"`);
        await queryRunner.query(`ALTER TABLE "lesson_progress" DROP CONSTRAINT "FK_eb4349e70765bb218bb4f833f68"`);
        await queryRunner.query(`ALTER TABLE "sync_history" DROP CONSTRAINT "FK_41c20ca17ff2890de04f660ef76"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_fae09ef9b1765a71a91475f8ba7"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_605baeb040ff0fae995404cea37"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_6227c61eff466680f9bb9933305"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_fe4917e809e078929fe517ab762"`);
        await queryRunner.query(`ALTER TABLE "state_audit" DROP CONSTRAINT "FK_a865049511f1e068f85cc5cacec"`);
        await queryRunner.query(`ALTER TABLE "anomalies" DROP CONSTRAINT "FK_e6a5e625a5305387f8565e3869f"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_4fe5cb57be94f7163c71ab3807c"`);
        await queryRunner.query(`ALTER TABLE "patterns" DROP CONSTRAINT "FK_e5c12879ffcd0cbbac1dfca738c"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_8f08ff70d9c14259219201ad445"`);
        await queryRunner.query(`ALTER TABLE "practice_progress" DROP CONSTRAINT "FK_fed92359515dfd602a1d8e04829"`);
        await queryRunner.query(`ALTER TABLE "player_level" DROP CONSTRAINT "FK_7d1fb4880813f3331b0bbd50004"`);
        await queryRunner.query(`ALTER TABLE "player_skill" DROP CONSTRAINT "FK_3368acdf2e65b24118fbbee2947"`);
        await queryRunner.query(`ALTER TABLE "power_up_purchase" DROP CONSTRAINT "FK_473ea9d9368c7468ff97803b245"`);
        await queryRunner.query(`ALTER TABLE "power_up_purchase" DROP CONSTRAINT "FK_544e9b97de456bac13b06bf2d74"`);
        await queryRunner.query(`ALTER TABLE "location_access" DROP CONSTRAINT "FK_70c1b3a369f14032a95d797a975"`);
        await queryRunner.query(`ALTER TABLE "custom_game_modes" DROP CONSTRAINT "FK_c9488b539ed99f0866be8c7c84d"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_302670923e49b67d7f4e9772f64"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_18b10b5df91ce11abe764e6edda"`);
        await queryRunner.query(`ALTER TABLE "generated_content" DROP CONSTRAINT "FK_458f45d0fa6ef378f16113f3680"`);
        await queryRunner.query(`ALTER TABLE "config_audit" DROP CONSTRAINT "FK_ff0bc659e4f0abbecd84b3c8006"`);
        await queryRunner.query(`ALTER TABLE "user_achievement" DROP CONSTRAINT "FK_843ecd1965f1aac694875674a18"`);
        await queryRunner.query(`ALTER TABLE "user_achievement" DROP CONSTRAINT "FK_2a418515c335cab7c5ba70c28b3"`);
        await queryRunner.query(`ALTER TABLE "user_activity" DROP CONSTRAINT "FK_c8d8d7cfc6e3433e725339c952b"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_3c658637d779605a5f17a018c81"`);
        await queryRunner.query(`ALTER TABLE "player_rooms" DROP CONSTRAINT "FK_baf7e3898baabc477aa4d8058a6"`);
        await queryRunner.query(`ALTER TABLE "player_rooms" DROP CONSTRAINT "FK_85404222998d4d527b2144180f0"`);
        await queryRunner.query(`ALTER TABLE "game_sessions" DROP CONSTRAINT "FK_4fa37b6649feb118785237853e5"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_70ff19adfe86eac7f48e1524973"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_59de462f9ce130da142e3b5a9f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00d4d9d863ebe837fc0bb9bbda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bff99233fe88934d1d9ec5c50b"`);
        await queryRunner.query(`DROP TABLE "reports_anomalies_anomalies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_669266aed514df75c08a134bce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ce5ba390f8fc32878ee8a0cd6"`);
        await queryRunner.query(`DROP TABLE "song_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9c3f442fe422fb48f6b6ae933"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c2e96f0074f11d1a9917dd4f4"`);
        await queryRunner.query(`DROP TABLE "coupon_applicable_items_store_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fec553a0f27c6f5da0a56d2b98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cd87de62a2c41e479f0e9e3e7"`);
        await queryRunner.query(`DROP TABLE "players_game_sessions_game_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_763cd9da7c8b086ab1a0f75331"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4e830a879d5346795b76e1047"`);
        await queryRunner.query(`DROP TABLE "tournament_participants_users"`);
        await queryRunner.query(`DROP TABLE "lesson_progress"`);
        await queryRunner.query(`DROP TABLE "music_lesson"`);
        await queryRunner.query(`DROP TABLE "quiz"`);
        await queryRunner.query(`DROP TABLE "genre_history"`);
        await queryRunner.query(`DROP TABLE "artist"`);
        await queryRunner.query(`DROP TABLE "shares"`);
        await queryRunner.query(`DROP TYPE "public"."shares_platform_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shares_type_enum"`);
        await queryRunner.query(`DROP TABLE "activity_items"`);
        await queryRunner.query(`DROP TABLE "share_analytics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dadc1a0a962be5e8d09b33c4e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2c9659e7f5ea5b2994fbe81e1"`);
        await queryRunner.query(`DROP TABLE "wagers"`);
        await queryRunner.query(`DROP TYPE "public"."wagers_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14b0fcce98762aa70bb9cfd577"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbce738cd9b37246a250603447"`);
        await queryRunner.query(`DROP TABLE "sync_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41c20ca17ff2890de04f660ef7"`);
        await queryRunner.query(`DROP TABLE "sync_history"`);
        await queryRunner.query(`DROP TABLE "transaction"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "state_audit"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9655d1d49ca2af5f7a350cfa1c"`);
        await queryRunner.query(`DROP TABLE "user_genre_preferences"`);
        await queryRunner.query(`DROP TYPE "public"."user_genre_preferences_genre_enum"`);
        await queryRunner.query(`DROP TABLE "game_state"`);
        await queryRunner.query(`DROP TABLE "scoring"`);
        await queryRunner.query(`DROP TABLE "anomalies"`);
        await queryRunner.query(`DROP TABLE "replays"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TABLE "patterns"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e69e62f014eed5c621710bdd0"`);
        await queryRunner.query(`DROP TABLE "songs"`);
        await queryRunner.query(`DROP TYPE "public"."songs_difficulty_enum"`);
        await queryRunner.query(`DROP TYPE "public"."songs_genre_enum"`);
        await queryRunner.query(`DROP TYPE "public"."songs_status_enum"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "practice_progress"`);
        await queryRunner.query(`DROP TYPE "public"."practice_progress_genre_enum"`);
        await queryRunner.query(`DROP TABLE "player_level"`);
        await queryRunner.query(`DROP TABLE "player_stats"`);
        await queryRunner.query(`DROP TABLE "player_skill"`);
        await queryRunner.query(`DROP TABLE "power_up_purchase"`);
        await queryRunner.query(`DROP TABLE "power_up"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e63bfae8ba1bbd2614be36731a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d7c521e6b5e4ed12810185797"`);
        await queryRunner.query(`DROP TABLE "game_results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4af4449083c75c65d82351d150"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94015b1d60e640eb05a1a7944b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cda49a36795f20bc974f9d1a15"`);
        await queryRunner.query(`DROP TABLE "leaderboard_round_results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_301ed31d932bcfdd22ed87ed59"`);
        await queryRunner.query(`DROP TABLE "token_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc34d4f79551898149eadc54b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66d338c28e4f3fbd870043b9bf"`);
        await queryRunner.query(`DROP TABLE "location_access"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5de21ea3c57035888d98d5bc4c"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TABLE "difficulties"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_783c305cc0c33e930cbbe749ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb82c5bb484e891ad7c43c9cb0"`);
        await queryRunner.query(`DROP TABLE "migration_history"`);
        await queryRunner.query(`DROP TABLE "custom_game_modes"`);
        await queryRunner.query(`DROP TABLE "migration_lock"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89fa5b280771988b72142ffc91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_887cd1659f8b661e1ea7c9804f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5985996616f6f9f41503cb82d"`);
        await queryRunner.query(`DROP TABLE "backup_metadata"`);
        await queryRunner.query(`DROP TABLE "coupon_usage"`);
        await queryRunner.query(`DROP TABLE "coupon"`);
        await queryRunner.query(`DROP TYPE "public"."coupon_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coupon_discounttype_enum"`);
        await queryRunner.query(`DROP TABLE "store_item"`);
        await queryRunner.query(`DROP TABLE "generated_content"`);
        await queryRunner.query(`DROP TABLE "template"`);
        await queryRunner.query(`DROP TABLE "config_audit"`);
        await queryRunner.query(`DROP TABLE "config_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1143abb8c3fad8b06dd857a8c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6a19d4b4f6c62dcd29daa497e"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ba6fa4785e1ad503bd8fedf79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a7ed52c492d5bcd9ac6a1bece"`);
        await queryRunner.query(`DROP TABLE "song_category_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0c4f43fe640b3a7e1e070833a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77d0085801058cf4f3280aa456"`);
        await queryRunner.query(`DROP TABLE "user_progression_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb2ca8964c8aa32e3cc43a9dee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3553b0aad43bdfe497dcd7cc86"`);
        await queryRunner.query(`DROP TABLE "player_engagement_metrics"`);
        await queryRunner.query(`DROP TABLE "user_achievement"`);
        await queryRunner.query(`DROP TABLE "achievement"`);
        await queryRunner.query(`DROP TYPE "public"."achievement_category_enum"`);
        await queryRunner.query(`DROP TABLE "user_activity"`);
        await queryRunner.query(`DROP TABLE "leaderboards"`);
        await queryRunner.query(`DROP TABLE "chat_rooms"`);
        await queryRunner.query(`DROP TABLE "players"`);
        await queryRunner.query(`DROP TYPE "public"."players_status_enum"`);
        await queryRunner.query(`DROP TABLE "player_rooms"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TABLE "game_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."game_sessions_status_enum"`);
        await queryRunner.query(`DROP TABLE "tournament"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "referrals"`);
        await queryRunner.query(`DROP TYPE "public"."referrals_status_enum"`);
    }

}
